services:
  app:
    image: registry.cn-chengdu.aliyuncs.com/promonkeyli/website-go:latest
    container_name: website-go
    ports:
      - "8081:8081"
    networks:
      - website
  nginx:
    image: nginx:latest
    container_name: website-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/nginx-certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - website
volumes:
  mysql-data:
networks:
  website:
    driver: bridge